### ISSUE TITLE
How to scale spritesheet animation? 

### ISSUE THREAD

**Issue by ankitpate1** [NachoSoto/NSBSpritesheetLayer#2]
I am using NSBSpritesheetLayer for animation from spritesheet in Swift UIKit. But when i try to scale NSBSpritesheetLayer, animation images do not scale.I tried changing layer's frame and transform both but none of them worked. Is there any way i can scale animation view to match parent view ?

**Comment by NachoSoto** [comment]
That's probably because the layer's frame [is updated at every frame](https://github.com/NachoSoto/NSBSpritesheetLayer/blob/master/NSBSpritesheetLayer/Classes/NSBSpritesheetLayer.m#L110). What you want to do is wrap the `NSBSpritesheetLayer` into a parent layer, and animate that one.

Let me know if that solves your problem!
